apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: echo1-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - echo.m1g.pp.ua
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo1
spec:
  hosts:
  - echo.m1g.pp.ua
  gateways:
  - echo1-gateway
  http:
    - route:
      - destination:
          host: echo1
        port:
          number: 80
